# Generated by Django 5.1.7 on 2025-03-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_status_4a0a95_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_due_dat_bce847_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
